name: Docker Image Build & Release

on:
  push:
    branches: [ trunk ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Package JAR
      run: mvn clean install && \
        ls /home/runner/.m2/repository/org/dbio/dbio-fhir-proxy/*-SNAPSHOT/dbio-fhir-proxy-*-SNAPSHOT.jar | head -1 | xargs -i cp {} $HOME/app.jar
    - name: Build Docker image
      run: docker build .
            --tag ${{ secrets.DOCKERHUB_USER }}/dbio-fhir-proxy:$GITHUB_SHA \
            --tag ${{ secrets.DOCKERHUB_USER }}/dbio-fhir-proxy:latest
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_KEY }}
    - name: Push Docker image
      run: docker push --all-tags ssheldharv/dbio-fhir-proxy
