name: Docker Image Build & Release

on:
  push:
    branches: [ trunk ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build . --tag ssheldharv/dbio-fhir-proxy:${{ steps.vars.outputs.sha_short }} --tag ssheldharv/dbio-fhir-proxy:latest
    - name: Push Docker image
      run: docker push --all-tags ssheldharv/dbio-fhir-proxy
