name: Docker Image Build & Release

on:
  push:
    branches: [ trunk, docker-test ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with maven
      run: mvn clean package
        
    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_KEY }}
    
    - name: Push Docker image
      run: docker push --all-tags ssheldharv/dbio-fhir-proxy
