name: Docker Image Build & Release

on:
  push:
    branches: [ trunk, docker-build ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Package JAR
      run: |
        mvn clean package
        mv target/dbio-fhir-proxy*-with-dependencies.jar target/dbio-fhir-proxy-1.0-SNAPSHOT.jar
        mvn spring-boot:repackage
    - name: Build Docker image
      run: docker build . --tag ssheldharv/dbio-fhir-proxy:$GITHUB_SHA --tag ssheldharv/dbio-fhir-proxy:latest
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_KEY }}
    - name: Push Docker image
      run: docker push --all-tags ssheldharv/dbio-fhir-proxy
