name: Docker Image Build & Release

on:
  push:
    branches: [ trunk, docker-test ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with maven
      run: mvn clean package
        
    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_KEY }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        pull: true
        push: true
        #cache-from: type=registry,ref=ssheldharv/dbio-fhir-proxy:latest
        #cache-to: type=inline
        tags: latest
        #build-args: PROFILE=nectar,ARG2=test
