name: Docker Image Build & Release

on:
  push:
    branches: [ trunk, use-docker-mvn ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Package JAR
      run: mvn clean jar:jar docker:build -Ddocker.name=${{ secrets.DOCKERHUB_USER }}/dbio-fhir-proxy
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_KEY }}
    - name: Push Docker image
      run: docker push --all-tags ${{ secrets.DOCKERHUB_USER }}/dbio-fhir-proxy
