# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  pull_request:
    branches: [ trunk ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Extract signing key
      env:
        PEM: ${{ secrets.FHIR_PROXY_SIGNING_PEM }}
      run: echo "$PEM" > signing.pem
    - name: Build protocol-client with SBT
      working-directory: ./protocol-client
      env:
        - JWT_SIGNING_KEY: ./signing.pem
        - THIRD_PARTY_ETH_ADDRESS: ${{ secrets.THIRD_PARTY_ETH_ADDRESS }}
        - THIRD_PARTY_PRIVATE_KEY: ${{ secrets.THIRD_PARTY_PRIVATE_KEY }}
        - THIRD_PARTY_EMAIL: ${{ secrets.THIRD_PARTY_EMAIL }}
      run: sbt -Djava.library.path=./bin ";clean;scalafmtCheckAll;scalafixAll --check;test;publishM2"
    - name: Build FHIR Proxy with Maven
      run: mvn clean install
